name: branch-build
on:
  push:
    branches-ignore:
      - 'staging'
      - 'master'
jobs:
  build:
    name: ${{ github.ref_name }}-build
    uses: ./.github/workflows/build.yaml
    secrets:
      DOTENV: ${{ secrets.DOTENV_STAGING }}

  test:
    needs: build
    name: ${{ github.ref_name }}-test
    uses: ./.github/workflows/test.yaml
    secrets:
      CMD_DIR: ${{ secrets.CMD_DIR_STAGING }}
      IMG_DIR: ${{ secrets.IMG_DIR_STAGING }}

  clean:
    needs: test
    if: always()
    name: ${{ github.ref_name }}-clean
    uses: ./.github/workflows/clean.yaml
