name: production-build
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: production-build
    uses: ./.github/workflows/build.yaml
    secrets:
      DOTENV: ${{ secrets.DOTENV_PRODUCTION }}

  test:
    needs: build
    name: production-test
    uses: ./.github/workflows/test.yaml
    secrets:
      CMD_DIR: ${{ secrets.CMD_DIR_PRODUCTION }}
      IMG_DIR: ${{ secrets.IMG_DIR_PRODUCTION }}

  deploy:
    needs: test
    name: production-deploy
    runs-on: self-hosted
    steps:
      - name: stop & remove outdated container
        run: |  
          docker container rm -f discordbot-production
      - name: start production
        run: |
          docker run -i -t -d --restart always --name discordbot-production \
          -v ${{ secrets.IMG_DIR_PRODUCTION }}:/app/images \
          -v ${{ secrets.CMD_DIR_PRODUCTION }}:/app/commands \
          discordbot:master
