name: production-build
on:
  push: 
    branches:
      - master
jobs:
  build:
    name: production-build
    uses: ./.github/workflows/build.yaml
    secrets:
      DOTENV: ${{ secrets.DOTENV_PRODUCTION }}

  test:
    needs: build
    name: production-test
    uses: ./.github/workflows/test.yaml
    secrets:
      CMD_DIR: ${{ secrets.CMD_DIR_PRODUCTION }}
      IMG_DIR: ${{ secrets.IMG_DIR_PRODUCTION }}

  deploy:
    needs: test
    name: production-deploy
    runs-on: self-hosted
    steps:
      - name: stop & remove outdated container
        run: |  
          docker container rm -f discordbot-production
      - name: start production
        run: |
          docker run -i -t -d --restart always --name discordbot-production \
          -v /discordbot/images:/discordbot/images \
          -v /discordbot/commands:/discordbot/commands \
          discordbot:master

  tag-revert:
    name: tag revert commit
    runs-on:
      self-hosted
    steps:
      - name: create tag
        run: echo tagging
      - name: push tag 
        run: echo pushing
      
