name: Test Build
on:
  workflow_call:
    secrets:
      IMG_DIR:
        description: Image directory to mount when running self-test
      CMD_DIR:
        description: Command directory to mount when running self-test

jobs:
  self-test:
    runs-on: 
      self-hosted
    steps:
      - name: run test
        run: |
          docker run --name discordbot-test \
          -v ${{ secrets.IMG_DIR }}:/app/images \
          -v ${{ secrets.CMD_DIR }}:/app/commands \
          discordbot:${{ github.ref_name }} \
          node /app/discordBot.js test

  remove-container:
    needs: self-test
    if: always()
    runs-on:
      self-hosted
    steps:
      - name: remove test container
        run: |
          docker container rm discordbot-test
